#!/usr/bin/env node
/**
 * PostToolUse Hook - Kanban workflow automation
 *
 * Layer 1: Plan state tracking - keeps .current-plan.json in sync
 * Layer 2: Kanban completion handler - moves issues and detects batch completion
 */

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd();

async function main() {
  let input = '';
  try {
    input = fs.readFileSync(0, 'utf8');
  } catch (e) {
    process.exit(0);
  }

  let data = {};
  try {
    data = JSON.parse(input);
  } catch (e) {
    process.exit(0);
  }

  const toolName = data.tool_name || '';

  // Layer 1a: Track plan file writes
  if (toolName === 'Write') {
    const filePath = data.tool_input?.file_path || '';
    const normalizedPath = filePath.replace(/\\/g, '/');

    if (normalizedPath.includes('.claude/plans/') && filePath.endsWith('.md')) {
      const planStateFile = path.join(projectDir, '.claude', '.current-plan.json');
      const planName = path.basename(filePath, '.md');
      const state = {
        planFile: path.resolve(projectDir, filePath),
        summary: `Plan: ${planName}`,
        timestamp: new Date().toISOString()
      };

      try {
        fs.writeFileSync(planStateFile, JSON.stringify(state, null, 2));
        console.error('');
        console.error('✅ Plan state updated:');
        console.error(`   File: ${filePath}`);
        console.error('');
      } catch (e) {
        // Non-critical
      }
    }
  }

  // Layer 1b: Plan mode exit verification
  if (toolName === 'ExitPlanMode') {
    const planFile = data.tool_input?.planFile || '';
    const planDir = path.join(projectDir, '.claude', 'plans');
    const planStateFile = path.join(projectDir, '.claude', '.current-plan.json');

    if (!fs.existsSync(planFile)) {
      console.error('');
      console.error('⚠️  PLAN MODE EXIT: Plan file was never created!');
      console.error(`Expected: ${planFile}`);
      console.error('');

      if (!fs.existsSync(planDir)) {
        fs.mkdirSync(planDir, { recursive: true });
      }

      const timestamp = new Date().toISOString().split('T')[0];
      const placeholderPath = path.join(planDir, `${timestamp}-PLAN-incomplete.md`);
      const placeholderContent = `# Plan (Incomplete)\n\n**Created:** ${timestamp}\n**Status:** INCOMPLETE - ExitPlanMode called but plan file was never written\n\n**Expected Path:** ${planFile}\n\n## Note\n\nReview the conversation history and update this plan file.\n\n_Auto-generated by PostToolUse hook_\n`;

      try {
        fs.writeFileSync(placeholderPath, placeholderContent);
        console.error(`Created placeholder: ${placeholderPath}`);
      } catch (e) {
        // Non-critical
      }

      try {
        if (fs.existsSync(planStateFile)) fs.unlinkSync(planStateFile);
      } catch (e) { /* ignore */ }
    }

    process.exit(0);
  }

  // Layer 1c: Update plan state when plan files are written with final path
  if (['Write', 'Edit'].includes(toolName)) {
    const filePath = data.tool_input?.file_path || '';
    const normalizedPath = filePath.replace(/\\/g, '/');
    updatePlanStateIfNeeded(filePath, normalizedPath);
  }

  // Layer 2: Kanban completion handler
  handleKanbanCompletion(data);

  process.exit(0);
}

/**
 * Update .current-plan.json when a properly-named plan file is written.
 */
function updatePlanStateIfNeeded(filePath, normalizedPath) {
  if (!normalizedPath.includes('.claude/plans/') || !normalizedPath.endsWith('.md')) return;

  const planPattern = /^\d{4}-\d{2}-\d{2}-.+\.md$/;
  const filename = normalizedPath.split('/').pop();
  if (!planPattern.test(filename)) return;

  const stateFile = path.join(projectDir, '.claude', '.current-plan.json');
  const planStateDir = path.dirname(stateFile);

  try {
    if (!fs.existsSync(planStateDir)) {
      fs.mkdirSync(planStateDir, { recursive: true });
    }

    let existingState = null;
    if (fs.existsSync(stateFile)) {
      try { existingState = JSON.parse(fs.readFileSync(stateFile, 'utf8')); } catch (e) { /* ignore */ }
    }

    const state = {
      planFile: path.resolve(projectDir, filePath),
      summary: existingState?.summary || `Plan: ${filename}`,
      timestamp: new Date().toISOString()
    };

    fs.writeFileSync(stateFile, JSON.stringify(state, null, 2));
    console.error('');
    console.error('ℹ️  Plan state updated:', filename);
    console.error('');
  } catch (e) {
    // Non-critical
  }
}

/**
 * Layer 2: Handle Kanban completion - move issues and detect batch completion
 */
function handleKanbanCompletion(data) {
  const toolName = data.tool_name || '';
  if (toolName !== 'Skill') return;

  const skillName = data.tool_input?.skill || '';
  const skillArgs = data.tool_input?.args || '';
  const result = data.tool_result;

  if (skillName !== 'autodev') return;

  // Only handle issue-driven autodev sessions
  const issueMatch = skillArgs.match(/--issue\s+(\d+)/);
  if (!issueMatch) return;

  const issueNumber = issueMatch[1];

  // Check if autodev was successful
  const isSuccess = result?.success !== false &&
                    !JSON.stringify(result).includes('error') &&
                    !JSON.stringify(result).includes('failed');

  if (!isSuccess) {
    console.error('');
    console.error(`KANBAN: Issue #${issueNumber} autodev did not complete successfully`);
    console.error('Issue remains in in-progress column');
    return;
  }

  console.error('');
  console.error(`KANBAN: Issue #${issueNumber} completed successfully`);

  // Move issue to Review column
  try {
    const moveResult = spawnSync('gh', [
      'issue', 'edit', issueNumber,
      '--add-label', 'review',
      '--remove-label', 'in-progress'
    ], { cwd: projectDir, encoding: 'utf8', stdio: 'pipe' });

    if (moveResult.status === 0) {
      console.error(`KANBAN: Issue #${issueNumber} moved to Review`);
    } else {
      console.error(`KANBAN: Failed to move issue #${issueNumber} to Review`);
    }
  } catch (e) {
    console.error(`KANBAN: Error moving issue: ${e.message}`);
  }

  // Log completion to state file
  try {
    const logsDir = path.join(projectDir, 'logs');
    if (!fs.existsSync(logsDir)) fs.mkdirSync(logsDir, { recursive: true });

    const stateFile = path.join(logsDir, 'kanban_state.json');
    let state = { recently_completed: [], batch_start_time: null };

    if (fs.existsSync(stateFile)) {
      try { state = JSON.parse(fs.readFileSync(stateFile, 'utf8')); } catch (e) { /* use default */ }
    }

    if (!state.recently_completed) state.recently_completed = [];
    state.recently_completed.push({
      issue: issueNumber,
      completed: new Date().toISOString()
    });
    state.recently_completed = state.recently_completed.slice(-20);

    fs.writeFileSync(stateFile, JSON.stringify(state, null, 2));
  } catch (e) {
    console.error(`KANBAN: Error logging completion: ${e.message}`);
  }

  // Check if the full batch is done
  checkBatchCompletion();

  console.error('');
}

/**
 * Check if the batch is complete - no remaining ready or in-progress issues.
 * Prints a batch completion banner if all work has moved to review.
 */
function checkBatchCompletion() {
  try {
    const readyResult = spawnSync('gh', [
      'issue', 'list', '--label', 'ready', '--state', 'open', '--limit', '1', '--json', 'number'
    ], { cwd: projectDir, encoding: 'utf8', stdio: 'pipe' });

    const inProgressResult = spawnSync('gh', [
      'issue', 'list', '--label', 'in-progress', '--state', 'open', '--limit', '1', '--json', 'number'
    ], { cwd: projectDir, encoding: 'utf8', stdio: 'pipe' });

    if (readyResult.status !== 0 || inProgressResult.status !== 0) return;

    let readyIssues = [];
    let inProgressIssues = [];
    try {
      readyIssues = JSON.parse(readyResult.stdout || '[]');
      inProgressIssues = JSON.parse(inProgressResult.stdout || '[]');
    } catch (e) { return; }

    if (readyIssues.length === 0 && inProgressIssues.length === 0) {
      const reviewResult = spawnSync('gh', [
        'issue', 'list', '--label', 'review', '--state', 'open', '--limit', '50', '--json', 'number'
      ], { cwd: projectDir, encoding: 'utf8', stdio: 'pipe' });

      let reviewCount = '?';
      try {
        reviewCount = JSON.parse(reviewResult.stdout || '[]').length;
      } catch (e) { /* keep '?' */ }

      console.error('');
      console.error('╔══════════════════════════════════════════════╗');
      console.error('║         BATCH COMPLETE                       ║');
      console.error('╠══════════════════════════════════════════════╣');
      console.error(`║ Tasks moved to review: ${String(reviewCount).padEnd(21)}║`);
      console.error('║                                              ║');
      console.error('║ Next steps:                                  ║');
      console.error('║  1. Review tasks in "review" column          ║');
      console.error('║  2. Close completed tasks or send back       ║');
      console.error('║  3. Create follow-up issues if needed        ║');
      console.error('║  4. Run /batch again for next cycle          ║');
      console.error('╚══════════════════════════════════════════════╝');
      console.error('');
    }
  } catch (e) {
    // Non-critical - silently ignore
  }
}

main();
