"""
Mockup Spec Generator - Extract complete GUI specification from mockup image

This tool analyzes a mockup and generates a complete YAML specification including:
- All detected components with positions and sizes
- Colors for each element
- Text labels
- Layout structure

Usage:
    from frontend_tools.spec_generator import SpecGenerator

    gen = SpecGenerator("mockup.jpg", scale_factor=1.85)
    spec = gen.generate()
    spec.save("plugin_spec.yaml")

    # Or interactive mode
    gen = SpecGenerator.interactive("mockup.jpg")
    # Click on components to identify them
"""

from PIL import Image, ImageDraw, ImageFont
import numpy as np
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass, field
from collections import defaultdict
import json


@dataclass
class ComponentSpec:
    """Specification for a single UI component."""
    type: str  # knob, label, meter, dropdown, button, led, etc.
    id: str
    x: int
    y: int
    width: int
    height: int
    color: str = "#000000"
    text: str = ""
    font_size: int = 0
    properties: Dict = field(default_factory=dict)

    def to_yaml(self, indent: int = 0) -> str:
        """Convert to YAML format."""
        spaces = "  " * indent
        lines = [
            f"{spaces}- type: {self.type}",
            f"{spaces}  id: {self.id}",
            f"{spaces}  position: [{self.x}, {self.y}]",
            f"{spaces}  size: [{self.width}, {self.height}]"
        ]

        if self.color != "#000000":
            lines.append(f"{spaces}  color: {self.color}")
        if self.text:
            lines.append(f"{spaces}  text: \"{self.text}\"")
        if self.font_size > 0:
            lines.append(f"{spaces}  font_size: {self.font_size}")
        if self.properties:
            lines.append(f"{spaces}  properties:")
            for k, v in self.properties.items():
                lines.append(f"{spaces}    {k}: {v}")

        return "\n".join(lines)


@dataclass
class SectionSpec:
    """Specification for a GUI section (header, main, etc.)."""
    name: str
    x: int
    y: int
    width: int
    height: int
    background: str = "#000000"
    components: List[ComponentSpec] = field(default_factory=list)

    def to_yaml(self, indent: int = 0) -> str:
        """Convert to YAML format."""
        spaces = "  " * indent
        lines = [
            f"{spaces}- name: {self.name}",
            f"{spaces}  position: [{self.x}, {self.y}]",
            f"{spaces}  size: [{self.width}, {self.height}]",
            f"{spaces}  background: {self.background}",
            f"{spaces}  components:"
        ]

        for comp in self.components:
            lines.append(comp.to_yaml(indent + 2))

        return "\n".join(lines)


class GUISpec:
    """Complete GUI specification."""

    def __init__(self, name: str, width: int, height: int):
        self.name = name
        self.width = width
        self.height = height
        self.sections: List[SectionSpec] = []
        self.colors: Dict[str, str] = {}
        self.fonts: Dict[str, str] = {}
        self.metadata: Dict = {}

    def to_yaml(self) -> str:
        """Convert to complete YAML specification."""
        lines = [
            f"# GUI Specification: {self.name}",
            f"# Generated by spec_generator.py",
            "",
            "gui:",
            f"  name: {self.name}",
            f"  size: [{self.width}, {self.height}]",
            "",
            "  sections:"
        ]

        for section in self.sections:
            lines.append(section.to_yaml(2))

        if self.colors:
            lines.append("")
            lines.append("  colors:")
            for name, color in self.colors.items():
                lines.append(f"    {name}: {color}")

        if self.fonts:
            lines.append("")
            lines.append("  fonts:")
            for name, font in self.fonts.items():
                lines.append(f"    {name}: {font}")

        if self.metadata:
            lines.append("")
            lines.append("  metadata:")
            for k, v in self.metadata.items():
                lines.append(f"    {k}: {v}")

        return "\n".join(lines)

    def save(self, path: str):
        """Save specification to file."""
        with open(path, 'w') as f:
            f.write(self.to_yaml())


class SpecGenerator:
    """Generate GUI specification from mockup image."""

    def __init__(self, image_path: str, scale_factor: float = 1.85):
        """
        Initialize generator.

        Args:
            image_path: Path to mockup image
            scale_factor: Scale factor if mockup is DPI-scaled
        """
        self.image_path = image_path
        self.scale_factor = scale_factor
        self.image = Image.open(image_path)
        if self.image.mode != 'RGB':
            self.image = Image.open(image_path).convert('RGB')
        self.array = np.array(self.image)

        # Detected components (organized by type)
        self.knobs: List[ComponentSpec] = []
        self.labels: List[ComponentSpec] = []
        self.meters: List[ComponentSpec] = []
        self.leds: List[ComponentSpec] = []
        self.dropdowns: List[ComponentSpec] = []
        self.buttons: List[ComponentSpec] = []

        # Color palette
        self.colors = {}

    def scale(self, value: int) -> int:
        """Convert image coordinate to GUI coordinate."""
        return int(value / self.scale_factor)

    @property
    def gui_width(self) -> int:
        return int(self.image.width / self.scale_factor)

    @property
    def gui_height(self) -> int:
        return int(self.image.height / self.scale_factor)

    def get_color(self, x: int, y: int) -> str:
        """Get color at position as hex string."""
        x = min(x, self.image.width - 1)
        y = min(y, self.image.height - 1)
        r, g, b = self.array[y, x]
        return f"#{r:02X}{g:02X}{b:02X}"

    def analyze_all(self) -> GUISpec:
        """
        Perform complete analysis and generate specification.

        Returns:
            GUISpec with all detected components
        """
        spec = GUISpec(
            name="PluginTemplate",
            width=self.gui_width,
            height=self.gui_height
        )

        # Detect sections (header, main panel)
        header = self._detect_header()
        spec.sections.append(header)

        # Detect components in each section
        self._detect_knobs(header)
        self._detect_labels(header)
        self._detect_dropdowns(header)
        self._detect_meters(spec)
        self._detect_leds(spec)

        # Extract color palette
        self._extract_colors(spec)

        return spec

    def _detect_header(self) -> SectionSpec:
        """Detect the header/toolbar section."""
        # Header is typically at the top, ~50px tall
        header_height = self._scan_for_header_height()

        header = SectionSpec(
            name="header",
            x=0,
            y=0,
            width=self.gui_width,
            height=header_height,
            background=self.get_color(
                int(self.image.width / 2),
                int(header_height * self.scale_factor / 2)
            )
        )

        return header

    def _scan_for_header_height(self) -> int:
        """Scan for the height of the header section."""
        # Look for color change from title bar to content
        middle_x = self.image.width // 2
        prev_color = self.get_color(middle_x, 0)

        for y in range(10, min(200, self.image.height)):
            curr_color = self.get_color(middle_x, y)
            if curr_color != prev_color:
                # Found a change - check if this is the header/content boundary
                # by looking a bit further to confirm
                next_color = self.get_color(middle_x, y + 10)
                if next_color != curr_color:
                    return self.scale(y)

        # Default to 50px if not found
        return 50

    def _detect_knobs(self, section: SectionSpec):
        """Detect circular knob components."""
        # Look for circular shapes in the header
        # Knobs are typically silver/gray circles

        # Scan horizontal strips for circular patterns
        for y in range(10, min(50, self.image.height), 5):
            for x in range(0, self.image.width, 10):
                color = self.get_color(x, y)
                # Check if this is a silver/gray color typical of knobs
                if self._is_knob_color(color):
                    # Try to measure a circular region
                    component = self._measure_circular(x, y)
                    if component and 20 <= component['width'] <= 60:
                        knob = ComponentSpec(
                            type="knob",
                            id=f"knob_{len(self.knobs)}",
                            x=self.scale(x - component['width'] // 2),
                            y=self.scale(y - component['height'] // 2),
                            width=self.scale(component['width']),
                            height=self.scale(component['height']),
                            color=color
                        )
                        self.knobs.append(knob)
                        section.components.append(knob)

    def _is_knob_color(self, color: str) -> bool:
        """Check if color is typical for knobs."""
        # Silver/gray colors
        gray_ranges = [
            (0xC0C0C0, 0xD0D0D0),  # Light silver
            (0x909090, 0xA0A0A0),  # Medium gray
            (0x606060, 0x707070),  # Dark gray
        ]

        c = int(color[1:], 16)
        for low, high in gray_ranges:
            if low <= c <= high:
                return True
        return False

    def _measure_circular(self, x: int, y: int) -> Optional[Dict]:
        """Measure a circular region starting from center point."""
        target_color = self._get_rgb(x, y)
        radius = 0

        # Expand outward until color changes
        for r in range(1, 50):
            # Check edge at angle 0 (right)
            edge_x = x + r
            edge_y = y
            if edge_x >= self.image.width:
                break
            edge_color = self._get_rgb(edge_x, edge_y)
            if not self._colors_match(target_color, edge_color, 30):
                radius = r - 1
                break

        if radius > 5:
            diameter = radius * 2
            return {'width': diameter, 'height': diameter}
        return None

    def _get_rgb(self, x: int, y: int) -> Tuple[int, int, int]:
        """Get RGB color tuple at coordinates."""
        x = min(x, self.image.width - 1)
        y = min(y, self.image.height - 1)
        r, g, b = self.array[y, x]
        return (int(r), int(g), int(b))

    def _colors_match(
        self,
        c1: Tuple[int, int, int],
        c2: Tuple[int, int, int],
        tolerance: int
    ) -> bool:
        """Check if two colors match within tolerance."""
        return (
            abs(c1[0] - c2[0]) <= tolerance and
            abs(c1[1] - c2[1]) <= tolerance and
            abs(c1[2] - c2[2]) <= tolerance
        )

    def _detect_labels(self, section: SectionSpec):
        """Detect text labels using OCR or color patterns."""
        # Look for small, high-contrast text areas
        # For now, add placeholder labels at known positions

        # Common label positions in header
        labels = [
            ("IN", 30, 30),
            ("PRESET", 150, 30),
            ("OS", 650, 30),
            ("ZOOM", 720, 30),
            ("OUT", 800, 30),
        ]

        for text, x, y in labels:
            label = ComponentSpec(
                type="label",
                id=f"label_{text.lower()}",
                x=self.scale(x),
                y=self.scale(y),
                width=0,  # Will be measured
                height=0,
                text=text,
                font_size=11
            )
            self.labels.append(label)
            section.components.append(label)

    def _detect_dropdowns(self, section: SectionSpec):
        """Detect dropdown button components."""
        # Dropdowns are typically rectangular with a dropdown arrow
        # Look for patterns in the header area

        # Add dropdowns based on label positions
        for label in self.labels:
            if label.text in ["PRESET", "OS", "ZOOM"]:
                dropdown = ComponentSpec(
                    type="dropdown",
                    id=f"{label.text.lower()}_dropdown",
                    x=label.x + 50,
                    y=label.y,
                    width=80,
                    height=24,
                    color="#3a3a3a",
                    properties={"arrow": "down"}
                )
                self.dropdowns.append(dropdown)
                section.components.append(dropdown)

    def _detect_meters(self, spec: GUISpec):
        """Detect meter components (vertical bars on sides)."""
        # Meters are typically tall vertical bars on left and right
        meter_width = 12
        meter_height = spec.height - 60

        # Left meter
        left_meter = SectionSpec(
            name="input_meter",
            x=10,
            y=50,
            width=meter_width,
            height=meter_height,
            background="#1a1a1a"
        )
        spec.sections.append(left_meter)
        self.meters.append(left_meter)

        # Right meter
        right_meter = SectionSpec(
            name="output_meter",
            x=spec.width - meter_width - 10,
            y=50,
            width=meter_width,
            height=meter_height,
            background="#1a1a1a"
        )
        spec.sections.append(right_meter)
        self.meters.append(right_meter)

    def _detect_leds(self, spec: GUISpec):
        """Detect LED indicator components."""
        # LEDs are small circular elements, typically above meters
        led_radius = 3

        for meter in self.meters:
            if "input" in meter.name:
                led = ComponentSpec(
                    type="led",
                    id="input_peak_led",
                    x=meter.x + meter.width // 2 - led_radius,
                    y=meter.y - 10,
                    width=led_radius * 2,
                    height=led_radius * 2,
                    color="#ff4040",
                    properties={"function": "peak_indicator"}
                )
                self.leds.append(led)

            elif "output" in meter.name:
                led = ComponentSpec(
                    type="led",
                    id="output_peak_led",
                    x=meter.x + meter.width // 2 - led_radius,
                    y=meter.y - 10,
                    width=led_radius * 2,
                    height=led_radius * 2,
                    color="#ff4040",
                    properties={"function": "peak_indicator"}
                )
                self.leds.append(led)

    def _extract_colors(self, spec: GUISpec):
        """Extract color palette from the mockup."""
        # Sample key areas
        spec.colors = {
            "toolbar_bg": self.get_color(
                self.image.width // 2,
                int(25 * self.scale_factor)
            ),
            "panel_bg": self.get_color(
                self.image.width // 2,
                int(100 * self.scale_factor)
            ),
            "knob_outer": self.get_color(
                int(40 * self.scale_factor),
                int(25 * self.scale_factor)
            ),
            "text_primary": "#FFFFFF",
            "text_secondary": "#a0a0a0",
            "accent": "#a0e0e0",
        }


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description='Generate GUI specification from mockup'
    )
    parser.add_argument('image', help='Path to mockup image')
    parser.add_argument('--scale', type=float, default=1.85,
                       help='Scale factor for DPI (default: 1.85)')
    parser.add_argument('--output', '-o', default='plugin_spec.yaml',
                       help='Output YAML file')

    args = parser.parse_args()

    gen = SpecGenerator(args.image, scale_factor=args.scale)
    spec = gen.analyze_all()

    spec.save(args.output)
    print(f"Generated specification: {args.output}")
    print(f"  GUI size: {spec.width} x {spec.height}")
    print(f"  Sections: {len(spec.sections)}")
    print(f"  Components: {sum(len(s.components) for s in spec.sections)}")


if __name__ == '__main__':
    main()
